---
version: '3'

vars:
  RDMO_CONTAINER:
    sh: docker ps --format "{{.Names}}" | grep "rdmo" | grep "stamp"
      | grep -Po "^[0-9a-f]+"
  RDMO_APP_FOLDER: /vol/rdmo-app
  DDP_APP_FOLDER: /vol/ddp-app

tasks:
  default:
    desc: install ddp app into a running rdmo container
    cmds:
      - task: install

  install:
    desc: copy ddp app to docker and update local.py
    method: checksum
    cmds:
      - cmd: docker exec {{.RDMO_CONTAINER}} mkdir -p {{.DDP_APP_FOLDER}}
      - cmd: docker cp ./ {{.RDMO_CONTAINER}}:{{.DDP_APP_FOLDER}}
      - cmd: docker exec {{.RDMO_CONTAINER}} {{.DDP_APP_FOLDER}}/ddp_app/sh/add_app.sh
      - cmd: >-
          docker exec {{.RDMO_CONTAINER}} python {{.RDMO_APP_FOLDER}}/manage.py
          collectstatic --no-input
