---
version: '3'

vars:
  RDMO_CONTAINER:
    sh: docker ps --format "{{.Names}}" | grep "rdmo" | grep -Po
      "^[0-9a-f]+"
  RDMO_APP_FOLDER: /vol/rdmo-app
  DDP_APP_FOLDER: /vol/ddp-app

tasks:
  default:
    desc: default rdmo dockers build, from github master
    cmds:
      - cmd: ./sh/prepare/render_yaml.sh {{.DC_TEMP}} {{.CONFIG}}
      - cmd: ./sh/prepare/render_variables_env.sh .
      - task: build_dockers
      - task: log

  reload:
    cmds:
      - cmd: reload-browser

  install:
    desc: copy ddp app to docker and update local.py
    method: checksum
    cmds:
      - cmd: docker exec {{.RDMO_CONTAINER}} mkdir -p {{.DDP_APP_FOLDER}}
      - cmd: docker exec {{.RDMO_CONTAINER}} {{.DDP_APP_FOLDER}}/sh/add_app.sh
      - cmd: >-
          docker exec {{.RDMO_CONTAINER}} python {{.RDMO_APP_FOLDER}}/manage.py
          collectstatic --no-input
