version: '3'

vars:
    CONTAINER:
        sh: sh/get_container_name.sh

tasks:
    default:
        desc: default rdmo dockers build, from github master
        cmds:
            - cmd: ./sh/prepare/render_yaml.sh {{.DC_TEMP}} {{.CONFIG}}
            - cmd: ./sh/prepare/render_variables_env.sh .
            - task: build_dockers
            - task: log

    install:
        desc: copy ddp app to docker and update local.py
        sources:
            - ddp_app/static/*
        method: timestamp
        cmds:
            - cmd: docker exec {{.CONTAINER}} mkdir -p /home/rdmo/ddp-app
            - cmd: docker cp ./ {{.CONTAINER}}:/home/rdmo/ddp-app
            - cmd: docker exec {{.CONTAINER}} /home/rdmo/ddp-app/sh/add_app.sh
            - cmd: >-
                docker exec {{.CONTAINER}}
                python /home/rdmo/rdmo-app/manage.py collectstatic --no-input
            - cmd: reload-browser
